### ISSUE TITLE
Any way to continue building after error?

### ISSUE THREAD

**Issue by greatquux** [tliron/install-gnome-themes#35]
Hey, I am getting this error when building Numix-Base16-Ocean
      write src/gtk-3.20/dist/gtk-dark.css
      write src/gtk-3.20/dist/gtk.css
glib-compile-resources --sourcedir=src/gtk-3.0 src/gtk-3.0/gtk.gresource.xml
src/gtk-3.0/gtk.gresource.xml: Failed to locate “assets/checkbox-checked-dark.png” in any source directory.
make: *** [Makefile:21: gresource] Error 1

I know this is not your problem, it's a problem in the theme.  But is there any way to change the script so that it continues building after encountering an error?  I am just going to change my conf file to skip this theme for now.   I thought I knew shell scripting, but I can't for the life of me figure out why the non-zero exit from make causes the script to stop!

**Comment by tliron** [comment]
I opened a bug for this a while ago and there is no response from the theme author. See the README here, you can disable specific themes:
> You can also edit this file to skip themes. Just put the word "skip" instead of the git hash. For example, to skip Plano themes:
> ```
> github|lassekongo83|plano-theme|master skip
> ```
I think automatically continuing after building a theme fails is not such a good idea. If people are using this script as part of automation they would want to know if it fails.

By the way, the reason a non-zero exit causes the script to stop is due to `set -e`. This is actually a rather complex feature, but it tends to work "as expected" for handling errors.

**Comment by greatquux** [comment]
Wow, never knew that, thanks! Yeah it is complicated (reading https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#index-set).  I already skipped it and was able to build the rest of the themes, and wouldn't want to ask for a change that could break workflows, I'll just close this then, thanks again for the answer, it was bothering me and now I've learned something. :)
